### ISSUE TITLE
same bug .

### ISSUE THREAD

**Issue by Chingo-X** [Hax4us/Apkmod#11] opened 2019-10-01 20:28 UTC
![Screenshot_20191001-222239_Termux](https://user-images.githubusercontent.com/52953017/65997882-80e37e80-e49a-11e9-9e00-bb9a7f902bde.png)
hi, updated, added -a -b but same bugs .
long time issue still same, it take 2hrs and 
unable to build .
and i see u closing before i test, why ?
sry a question out of the topic 
tmux-bunch can works on pie ? 
thanks .

**Comment by Hax4us** [comment] 2019-10-02 03:07
Duplicate of https://github.com/Hax4us/Apkmod/issues/10

**Closed by Hax4us** 2019-10-02 03:07 UTC
