### ISSUE TITLE
setup

### ISSUE THREAD

**Issue by nichu8** [Hax4us/Apkmod#15] opened 2019-10-21 12:39 UTC
sh setup.sh
[!] Alpine is already installed
Do you want to reinstall ? (type "y" for yes or "n" for no) : y
--2019-10-21 17:49:43--  https://raw.githubusercontent.com/Hax4us/TermuxAlpine/master/TermuxAlpine.sh
Resolving raw.githubusercontent.com... 151.101.8.133
Connecting to raw.githubusercontent.com|151.101.8.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 5796 (5.7K) [text/plain]
Saving to: ‘TermuxAlpine.sh.2’

TermuxAlpine.s 100%   5.66K  8.67KB/s    in 0.7s

2019-10-21 17:49:44 (8.67 KB/s) - ‘TermuxAlpine.sh.2’ saved [5796/5796]

[!] Alpine is already installed
Do you want to reinstall ? (type "y" for yes or "n" for no) : y

 You are going to install Alpine in termux ;) Cool
 press ENTER to continue

 [*] Checking host architecture ...
 [*] Updating apt cache...
 [*] Checking for all required tools...
 • proot is OK
 • bsdtar is OK
 • curl is OK
 [*] Getting tar file...

##                                                     5.2%curl: (56) Recv failure: Software caused connection abort

 [*] Getting SHA ...

#################################################### 100.0%

 [*] Checking integrity of file...
 [*] The script will immediately terminate in case of integrity failure
 alpine-minirootfs-3.10.2-aarch64.tar.gz: FAILED
sha256sum: WARNING: 1 computed checksum did NOT match
 Sorry :( to say your downloaded linux file was corrupted or half downloaded, but don't worry, just rerun my script
mkdir: cannot create directory ‘/data/data/com.termux/files/usr/share/TermuxAlpine/root/.bind’: No such file or directory
proot warning: can't chdir("/home/.") in the guest rootfs: No such file or directory
proot info: default working directory is now "/"
proot error: '/usr/bin/env' not found (root = /data/data/com.termux/files/usr/share/TermuxAlpine, cwd = /, $PATH=(null))
fatal error: see `proot --help`.
--2019-10-21 17:51:10--  https://github.com/hax4us/Apkmod/raw/master/aapt/aarch64/aapt.tar.gz
Resolving github.com... 13.234.210.38
Connecting to github.com|13.234.210.38|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.githubusercontent.com/hax4us/Apkmod/master/aapt/aarch64/aapt.tar.gz [following]
--2019-10-21 17:51:11--  https://raw.githubusercontent.com/hax4us/Apkmod/master/aapt/aarch64/aapt.tar.gz
Resolving raw.githubusercontent.com... 151.101.8.133
Connecting to raw.githubusercontent.com|151.101.8.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 19148800 (18M) [application/octet-stream]
Saving to: ‘aapt.tar.gz’

aapt.tar.gz    100%  18.26M   144KB/s    in 5m 14s

2019-10-21 17:56:28 (59.6 KB/s) - ‘aapt.tar.gz’ saved [19148800/19148800]

tar: /data/data/com.termux/files/usr/share/TermuxAlpine/usr/lib: Cannot open: No such file or directory
tar: Error is not recoverable: exiting now
mv: cannot stat '/data/data/com.termux/files/usr/share/TermuxAlpine/usr/lib/android/aapt': No such file or directory
mv: cannot stat '/data/data/com.termux/files/usr/share/TermuxAlpine/usr/lib/android/aapt2': No such file or directory
/data/data/com.termux/files/usr/share/TermuxAlpine/opt/apktool.jar: No such file or directory
--2019-10-21 17:56:28--  https://github.com/hax4us/Apkmod/raw/master/apkmod.sh
Resolving github.com... 13.234.210.38
Connecting to github.com|13.234.210.38|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.githubusercontent.com/hax4us/Apkmod/master/apkmod.sh [following]
--2019-10-21 17:56:29--  https://raw.githubusercontent.com/hax4us/Apkmod/master/apkmod.sh
Resolving raw.githubusercontent.com... 151.101.8.133
Connecting to raw.githubusercontent.com|151.101.8.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 6360 (6.2K) [text/plain]
Saving to: ‘/data/data/com.termux/files/usr/bin/apkmod’

/data/data/com 100%   6.21K  --.-KB/s    in 0.02s

2019-10-21 17:56:30 (362 KB/s) - ‘/data/data/com.termux/files/usr/bin/apkmod’ saved [6360/6360]

chmod: cannot access '/data/data/com.termux/files/usr/share/TermuxAlpine/usr/bin/aapt': No such file or directory
chmod: cannot access '/data/data/com.termux/files/usr/share/TermuxAlpine/usr/bin/aapt2': No such file or directory
--2019-10-21 17:56:30--  https://github.com/hax4us/Apkmod/raw/master/scripts/apktool_termux.sh
Resolving github.com... 13.234.210.38
Connecting to github.com|13.234.210.38|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.githubusercontent.com/hax4us/Apkmod/master/scripts/apktool_termux.sh [following]
--2019-10-21 17:56:31--  https://raw.githubusercontent.com/hax4us/Apkmod/master/scripts/apktool_termux.sh
Resolving raw.githubusercontent.com... 151.101.8.133
Connecting to raw.githubusercontent.com|151.101.8.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 404 [text/plain]
Saving to: ‘apktool_termux.sh’

apktool_termux 100%     404  --.-KB/s    in 0s

2019-10-21 17:56:32 (7.05 MB/s) - ‘apktool_termux.sh’ saved [404/404]

--2019-10-21 17:56:32--  https://github.com/hax4us/Apkmod/raw/master/scripts/apktool_alpine.sh
Resolving github.com... 13.234.210.38
Connecting to github.com|13.234.210.38|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.githubusercontent.com/hax4us/Apkmod/master/scripts/apktool_alpine.sh [following]
--2019-10-21 17:56:33--  https://raw.githubusercontent.com/hax4us/Apkmod/master/scripts/apktool_alpine.sh
Resolving raw.githubusercontent.com... 151.101.8.133
Connecting to raw.githubusercontent.com|151.101.8.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 99 [text/plain]
Saving to: ‘apktool_alpine.sh’

apktool_alpine 100%      99  --.-KB/s    in 0s

2019-10-21 17:56:34 (1.83 MB/s) - ‘apktool_alpine.sh’ saved [99/99]

--2019-10-21 17:56:34--  https://github.com/hax4us/Apkmod/raw/master/scripts/apk.rb
Resolving github.com... 13.234.210.38
Connecting to github.com|13.234.210.38|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.githubusercontent.com/hax4us/Apkmod/master/scripts/apk.rb [following]
--2019-10-21 17:56:34--  https://raw.githubusercontent.com/hax4us/Apkmod/master/scripts/apk.rb
Resolving raw.githubusercontent.com... 151.101.8.133
Connecting to raw.githubusercontent.com|151.101.8.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 10835 (11K) [text/plain]
Saving to: ‘apk.rb’

apk.rb         100%  10.58K  --.-KB/s    in 0.1s

2019-10-21 17:56:35 (110 KB/s) - ‘apk.rb’ saved [10835/10835]

mv: cannot move 'apktool_alpine.sh' to '/data/data/com.termux/files/usr/share/TermuxAlpine/bin/apktool': No such file or directory
--2019-10-21 17:56:35--  https://github.com/hax4us/Apkmod/raw/master/patches/msf-5.0.48/msfvenom.patch
Resolving github.com... 13.234.210.38
Connecting to github.com|13.234.210.38|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.githubusercontent.com/hax4us/Apkmod/master/patches/msf-5.0.48/msfvenom.patch [following]
--2019-10-21 17:56:36--  https://raw.githubusercontent.com/hax4us/Apkmod/master/patches/msf-5.0.48/msfvenom.patch
Resolving raw.githubusercontent.com... 151.101.8.133
Connecting to raw.githubusercontent.com|151.101.8.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 342 [text/plain]
Saving to: ‘msfvenom.patch’

msfvenom.patch 100%     342  --.-KB/s    in 0s

2019-10-21 17:56:37 (7.28 MB/s) - ‘msfvenom.patch’ saved [342/342]

--2019-10-21 17:56:37--  https://github.com/hax4us/Apkmod/raw/master/patches/msf-5.0.48/payload_generator.rb.patch
Resolving github.com... 13.234.210.38
Connecting to github.com|13.234.210.38|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.githubusercontent.com/hax4us/Apkmod/master/patches/msf-5.0.48/payload_generator.rb.patch [following]
--2019-10-21 17:56:37--  https://raw.githubusercontent.com/hax4us/Apkmod/master/patches/msf-5.0.48/payload_generator.rb.patch
Resolving raw.githubusercontent.com... 151.101.8.133
Connecting to raw.githubusercontent.com|151.101.8.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 979 [text/plain]
Saving to: ‘payload_generator.rb.patch’

payload_genera 100%     979  --.-KB/s    in 0s

2019-10-21 17:56:38 (18.9 MB/s) - ‘payload_generator.rb.patch’ saved [979/979]

$

![Uploading Screenshot_20191021_180010_com.termux.jpg…]()
![Uploading Screenshot_20191021_175917_com.termux.jpg…]()
![Uploading Screenshot_20191021_180022_com.termux.jpg…]()

**Comment by Hax4us** [comment] 2019-10-22 04:23
Duplicate of https://github.com/Hax4us/Apkmod/issues/14

**Closed** 2019-10-22 04:22 UTC
